Category.create(category: '生活')
Category.create(category: '仕事')
Category.create(category: '趣味')
Category.create(category: '人間')
Category.create(category: 'アニメ・漫画・ゲーム')
Category.create(category: 'インターネット')
Category.create(category: 'その他')