Category.create(type: '生活')
Category.create(type: '仕事')
Category.create(type: '趣味')
Category.create(type: '人間')
Category.create(type: 'アニメ・漫画・ゲーム')
Category.create(type: 'インターネット')
Category.create(type: 'その他')